#!/usr/bin/env python3
"""Make the DANN-E gallery sprite sheets grid-perfect.

`11_sprite_redactor_drone.png` and `13_sprite_junior_compiler.png` were exported
at 1254x1254. Declared as a 4x4 sheet with 313x313 frames, that leaves each cell
at 1254 / 4 = 313.5 device pixels, so Phaser's integer 313px frame grid drifts up
to ~1.5px off the artist's cells on the later columns/rows.

The fix resamples each 1254x1254 sheet down to 1252x1252 with nearest-neighbour
sampling (no interpolation, so no new blended/anti-aliased colours are added).
1252 / 4 = 313 exactly, so the existing 313x313 frame declaration in
`src/game/danneAtlas.ts` becomes grid-perfect and every frame lands on an integer
boundary. Grid-aligned sheets (12, 14) are already exact and are left untouched.

Originals are backed up under `public/assets/_originals/` before overwriting.
"""

from __future__ import annotations

from pathlib import Path
import shutil

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SPRITE_DIR = ROOT / "public/assets/art-pack/danne-pack/sprites"
BACKUP_ROOT = ROOT / "public/assets/_originals/art-pack/danne-pack/sprites"
REPORT_PATH = ROOT / "docs/art/danne_gallery_sheet_grid.md"

COLS = 4
ROWS = 4
FRAME = 313

# frame grid * cols/rows -> exact grid-perfect target size.
TARGET_W = FRAME * COLS
TARGET_H = FRAME * ROWS

SHEETS = [
    "11_sprite_redactor_drone.png",
    "13_sprite_junior_compiler.png",
]


def color_count(image: Image.Image) -> int:
    colors = image.getcolors(maxcolors=2_000_000)
    return len(colors) if colors else -1


def fix_sheet(filename: str) -> tuple[str, tuple[int, int], tuple[int, int], int, int]:
    path = SPRITE_DIR / filename
    if not path.exists():
        raise FileNotFoundError(path)

    original = Image.open(path).convert("RGBA")
    before_size = original.size
    before_colors = color_count(original)

    if before_size == (TARGET_W, TARGET_H):
        return filename, before_size, before_size, before_colors, before_colors

    backup = BACKUP_ROOT / filename
    backup.parent.mkdir(parents=True, exist_ok=True)
    if not backup.exists():
        shutil.copy2(path, backup)

    # NEAREST keeps hard pixels: no interpolation, so no new anti-aliased colours.
    resized = original.resize((TARGET_W, TARGET_H), Image.Resampling.NEAREST)
    resized.save(path, optimize=False)

    return filename, before_size, resized.size, before_colors, color_count(resized)


def write_report(rows: list[tuple[str, tuple[int, int], tuple[int, int], int, int]]) -> None:
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# DANN-E Gallery Sheet Grid Fix",
        "",
        "Generated by `scripts/fix-danne-gallery-sheet-grid.py`.",
        "",
        "The gallery sprite sheets `11_sprite_redactor_drone.png` and",
        "`13_sprite_junior_compiler.png` were 1254x1254, which is not divisible by the",
        "declared 4x4 / 313px frame grid (1254 / 4 = 313.5). Each is resampled with",
        "nearest-neighbour sampling to 1252x1252 (4 x 313) so every frame lands on an",
        "integer boundary. Nearest-neighbour introduces no interpolated/anti-aliased",
        "colours. Only the gallery preview consumes these sheets; gameplay uses the",
        "separate `runtime_*` sheets, which are unchanged.",
        "",
        "Originals are backed up under `public/assets/_originals/art-pack/danne-pack/sprites/`.",
        "",
        "| Sheet | Before | After | Colors before | Colors after |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for filename, before, after, cb, ca in rows:
        lines.append(
            f"| `{filename}` | {before[0]}x{before[1]} | {after[0]}x{after[1]} | {cb} | {ca} |"
        )
    lines.append("")
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    rows = [fix_sheet(name) for name in SHEETS]
    write_report(rows)
    for filename, before, after, cb, ca in rows:
        print(f"{filename}: {before[0]}x{before[1]} -> {after[0]}x{after[1]} ({cb} -> {ca} colors)")
    print(f"Report: {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
